name: CI

on:
  push:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'

jobs:
  Build:
    name: Build ${{matrix.config.file}} (${{ matrix.Configuration }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release, Debug]
        config:
          - {target: spt, file: spt.dll}
          - {target: spt_2013, file: spt-2013.dll}
          - {target: spt_oe, file: spt-oe.dll}
          - {target: spt_bms, file: spt-bms.dll}
    steps:
      - name: Checkout SPT
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init -j $env:NUMBER_OF_PROCESSORS SPTLib
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -A Win32 -DCMAKE_BUILD_TYPE=${{matrix.Configuration}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target ${{matrix.config.target}} -j $env:NUMBER_OF_PROCESSORS --config ${{matrix.Configuration}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.config.file}} (${{matrix.Configuration}})
          path: ${{github.workspace}}/build/${{matrix.Configuration}}/${{matrix.config.file}}
          if-no-files-found: error
